### PR TITLE
lang: new translation english(en)

### PR DESCRIPTION
**Pull request by nikhil-nix**
using [MkDocs static i18n plugin](https://pypi.org/project/mkdocs-static-i18n/) and [suffix docs structure](https://ultrabug.github.io/mkdocs-static-i18n/getting-started/quick-start/#the-suffix-docs-structure-default)

### CODE REVIEW

**Comment by nikhil-nix** [comment]
I haven't added separate image files for the English version yet; both language versions are using the same media files from the /docs/assets/ directory. Please expect a one-week delay as I currently don't have access to Windows OS and necessary programs.

**Comment by nikhil-nix** [comment]
I used [gpt-translate](https://github.com/3ru/gpt-translate) and google translator to assist with the translation, refining it based on my understanding of English and Linux documentation. Kindly note that there may be a few inaccuracies, and some instructions might not perfectly convey the original message."

**Comment by Wenzhi-Ding** [comment]
Thank you so much for bringing this site to international users, Nikhil! I made some revisions to accommodate the multi-language version and state your credit for the English version on the index page in 7763ed6a0772d3c1eba44a88328b4e48ee9f43ac.

**Comment by nikhil-nix** [comment]
I am genuinely humbled by the recognition on the project webpage, Sir. It was an amazing revision for me to localize and go through this guide. My sincere gratitude to you for creating such a valuable resource.

I will update with separate images for English version soon!

**Comment by nikhil-nix** [comment]
I'm truly impressed by your academic work and projects. I share a strong passion for utilizing unique data sources in research and academia with solid background in economics and excellent technical skills.

I'd greatly appreciate it if you could inform me of any ongoing or upcoming projects where I could contribute. I'm enthusiastic about the prospect of working under your guidance and learning from your expertise.

**Comment by Wenzhi-Ding** [comment]
Thanks for your interest! I will gladly contribute if you have any academic things you want to discuss.

**Comment by nikhil-nix** [comment]
Thank you for being open to engaging in academic discussions with me, Sir. I have been exploring various research areas, including Fintech and Investment theory, and have been considering research questions that could benefit from your insights and guidance. I am also eager to gain more hands-on experience with data and empirical research.

To provide some context, I recently completed my master's in economics from the Indian Institute of Foreign Trade (IIFT) in Delhi. Since graduating a few months ago, I have been actively seeking opportunities to contribute to a project as an assistant or intern. Throughout my master's program, I demonstrated strong analytical and programming skills, and I have worked on several projects that showcase my proficiency in empirical exercises and data handling. One such relevant project involved rigorous analysis to verify CAPM using R: by collecting and analyzing closing prices of S&P 500 BSE stocks over 15 years, I calculated annualized returns and built a variance-covariance matrix. Additionally, I determined monthly returns for the S&P 500 BSE and performed regression analysis to empirically test the Security Market Line.

If you have any ongoing or upcoming projects that require an assistant or intern for data and research, I would be delighted to work under your guidance. Attached is my [CV](https://github.com/Wenzhi-Ding/Server-User-Guide/files/12673344/CV_Nikhil.16.pdf) for your reference, I am at your disposal for any further information you might need.

Thank you.

**Pull request merged**
